### ISSUE TITLE
"Page not found" after switching from Spring Boot to Micronaut

### ISSUE THREAD

**Issue by t-buss** [micronaut-projects/micronaut-spring#10]
Hello there,
I created a sample project with Spring Initialyzer. It's a simple shopping cart service, just for messing with Micronaut for Spring.

In [this](https://github.com/t-buss/micronaut-cart/commit/6432395348787898db962fe6ab2817005101e107) commit, I tried to switch from Spring to Micronaut (with the intention of building a GraalVM native binary later), following the official [documentation](https://micronaut-projects.github.io/micronaut-spring/latest/guide/index.html) . However, while the Spring version works as expected, the Micronaut version returns 404 for the endpoint:
`$ curl localhost:8080/1/products`
`{"_links":{"self":{"href":"/1/products","templated":false}},"message":"Page Not Found"}`

Below it the debugging output when the service tries to handle the request. Looks like the the controller is not found.

Thanks in advance!

`13:40:27.189 [nioEventLoopGroup-1-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
13:40:27.189 [nioEventLoopGroup-1-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
13:40:27.191 [nioEventLoopGroup-1-2] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@3684c550
13:40:27.248 [nioEventLoopGroup-1-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
13:40:27.248 [nioEventLoopGroup-1-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
13:40:27.248 [nioEventLoopGroup-1-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
13:40:27.248 [nioEventLoopGroup-1-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
13:40:27.277 [nioEventLoopGroup-1-2] DEBUG io.micronaut.http.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /1/products
13:40:27.296 [nioEventLoopGroup-1-2] DEBUG io.micronaut.http.server.netty.RoutingInBoundHandler - Matching route GET - /1/products
13:40:27.300 [nioEventLoopGroup-1-2] DEBUG io.micronaut.http.server.netty.RoutingInBoundHandler - No matching route found for URI /1/products and method GET
13:40:27.313 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.http.server.context.ServerRequestContextFilter
13:40:27.314 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.http.server.context.ServerRequestContextFilter] for type: class io.micronaut.http.server.context.ServerRequestContextFilter
13:40:27.314 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.context.ServerRequestContextFilter]
13:40:27.314 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Found concrete candidate [Definition: io.micronaut.http.server.context.ServerRequestContextFilter] for type: io.micronaut.http.server.context.ServerRequestContextFilter 
13:40:27.314 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Created bean [io.micronaut.http.server.context.ServerRequestContextFilter@2c9ca380] from definition [Definition: io.micronaut.http.server.context.ServerRequestContextFilter] with qualifier [null]
13:40:27.314 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Registering singleton bean io.micronaut.http.server.context.ServerRequestContextFilter@2c9ca380 for type [io.micronaut.http.server.context.ServerRequestContextFilter] using bean key io.micronaut.http.server.context.ServerRequestContextFilter
13:40:27.315 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.spring.web.ResponseEntityServerFilter
13:40:27.315 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.spring.web.ResponseEntityServerFilter] for type: class io.micronaut.spring.web.ResponseEntityServerFilter
13:40:27.315 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.spring.web.ResponseEntityServerFilter]
13:40:27.316 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Found concrete candidate [Definition: io.micronaut.spring.web.ResponseEntityServerFilter] for type: io.micronaut.spring.web.ResponseEntityServerFilter 
13:40:27.316 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Created bean [io.micronaut.spring.web.ResponseEntityServerFilter@1e255af2] from definition [Definition: io.micronaut.spring.web.ResponseEntityServerFilter] with qualifier [null]
13:40:27.316 [nioEventLoopGroup-1-2] DEBUG io.micronaut.context.DefaultBeanContext - Registering singleton bean io.micronaut.spring.web.ResponseEntityServerFilter@1e255af2 for type [io.micronaut.spring.web.ResponseEntityServerFilter] using bean key io.micronaut.spring.web.ResponseEntityServerFilter
13:40:27.604 [nioEventLoopGroup-1-2] DEBUG io.micronaut.http.server.netty.RoutingInBoundHandler - Encoding emitted response object [Page Not Found] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@54f5f647`

**Comment by graemerocher** [comment]
Looks like a misconfiguration of the build. You have to use `kapt`. The `annotationProcessor` scope is only for Java. See https://github.com/micronaut-projects/micronaut-spring/blob/master/examples/greeting-service-kotlin/build.gradle#L5 for an example Kotlin build

**Comment by t-buss** [comment]
@graemerocher thanks! Adding `kapt` to the mix worked! But I could imagine that others may fall into the same pitfall. 
How do you feel about changing this in the documentation under "2.1 Build Configuration"? I can open a PR highlighting the necessary dependencies for the specific languages.

**Comment by graemerocher** [comment]
Sure sounds like a great idea. PRs welcome!

**Comment by t-buss** [comment]
@graemerocher Working on the PR, but I cannot find anything on Groovy. What annotation processors are used for Groovy?
