### ISSUE TITLE
Micronaut for Spring doesn't work with Micronaut 2.x.

### ISSUE THREAD

**Issue by ilkin** [micronaut-projects/micronaut-spring#106]
Hi, Micronaut for Spring doesn't work with Micronaut 2.x. Builds and runs successfully, but doesn't register Controller and not found rest api. Also generate simple spring-boot project from launch  missed below plugins:
```
id "org.springframework.boot" version "2.2.3.RELEASE"
id "io.spring.dependency-management" version "1.0.6.RELEASE"
```

**Comment by ilopmar** [comment]
@ilkin can you please open an issue on https://github.com/micronaut-projects/micronaut-starter about the missing depedencies?

Regarding the compatibility, please see #57 and #58
