### ISSUE TITLE
Unsupported SB feature

### ISSUE THREAD

**Issue by tdanylchuk** [micronaut-projects/micronaut-spring#12]
Hello all!

The idea of running Spring Boot apps with AOT is tremendous, so I'm trying to convert my project from boot to micronaut with help of these libs, but unfortunately it's hard to investigate why thing not going in right way.
I'm using Spring boot + groovy + spring cloud config service (which is not that trivial compared to examples).

So I've started with small steps: creating Spring Boot project from scratch and adding micronaut dependencies, so I can start APP with spring syntax, but via micronaut engine.
Unfortunately, I've already faced an issue with next code in my configuration class:
```
 @Bean
    public ApplicationRunner applicationRunner() {
        return args -> System.out.println("HELLO THERE!!!");
    }
```
And application runner just not being invoked, although MVC annotations are working...

So the question is next, is it possible to run complicated SB application (with cloud dependencies and some more spring specific staff) via micronaut engine? Or everything which currently supported is only stuff in examples?

Thanks!

**Comment by graemerocher** [comment]
As mentioned in the docs running everything won't be possible and isn't the goal of the project. We're trying to build something that will allow you to share libraries between Micronaut and Spring and make it easier to migrate to Micronaut from Spring, but it won't support all Spring features nor provide a 1 to 1 mapping for every Spring feature.

As it happens I do think we should probably support the `ApplicationRunner` interface, so we will look into that.

In terms of getting the features you after, you can use the equivalent Micronaut features, for example Micronaut supports many of the features of Spring Cloud https://docs.micronaut.io/latest/guide/index.html#cloud
