### ISSUE TITLE
Support for Spring Data JPA 

### ISSUE THREAD

**Issue by kdabir** [micronaut-projects/micronaut-spring#13]
**Context:**
I am really interested in converting an existing Spring boot based project to micronaut. The smoothest way to to transition, I think is, leaving spring annotation as-is and use micronaut-spring project. 

The project relies heavily on Spring Data JPA (Pageable, Sorting, Specification for search) etc.

**Question/Feature Request:**
What is the way to convert the Spring Data Repos to Micronaut at compile time. I could not find any reference for that. Is that supported? If not, could this be treated as a feature request to support Spring Data JPA interfaces?

**Comment by graemerocher** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/1193

It is currently not supported, but may be in the near future

**Comment by graemerocher** [comment]
Implemented in Micronaut Data. See https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jdbc-spring
