### ISSUE TITLE
Provide Maven example

### ISSUE THREAD

**Issue by micaelgallego** [micronaut-projects/micronaut-spring#2]
First of all, congratulations for this amazing project.

I'm trying to use micronaut-spring with Maven (I'm stick in the past, I know). For that, I've tried to "merge" one micronaut example with the official micronaut-spring example (written with Gradle). I've been able to generate a working .jar, but when I try to create Graal native image, I have an error. It seems I am including some library in Maven .jar not included in Gradle .jar causing some trouble. 

The project and error information is in this repository: https://github.com/codeurjc/micronaut-spring-graal-maven-example

If you have a Maven working example, please share with us and you can forget this issue.

**Comment by graemerocher** [comment]
Example maven build can be found at https://github.com/micronaut-projects/micronaut-spring/commit/bdcb72e11c56553b6b0897d6502ad84c0af83b7b#diff-ddb88e6d76abb4da188c8c71a5bfe229

**Comment by micaelgallego** [comment]
graal-native-image branch lacks Maven version. Do you plan to include it?
