### ISSUE TITLE
Update examples to use build-time generation reflect.json file (starting from 1.1.0 framework version)

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-spring#20]
Hope the header is quite descriptive.
The hand-written Dockerfile seems very clumsy and that build-time enablement would be great.

**Comment by graemerocher** [comment]
Will do this once 1.1 is out. Thanks

**Comment by graemerocher** [comment]
https://github.com/micronaut-projects/micronaut-spring/commit/5fdba1156b420ee1cde10230ab4f1b4fce6e05b9
