### ISSUE TITLE
Publish new build for 3.1.x line (probably 3.1.1)

### ISSUE THREAD

**Issue by arixmkii** [micronaut-projects/micronaut-spring#206]
Please consider publishing new release on top of current 3.1.0 with this fix https://github.com/micronaut-projects/micronaut-spring/commit/dbf8b2863f06708ce57d5aa027ea04d8bcc22dfb

Before it was possible to use snapshot builds, but it seems that they are not available now in jfrog oss (at least with default config, which worked before with gradle 6.9).

**Comment by ilopmar** [comment]
We moved the snapshots to Sonatype OSS some months ago. See https://docs.micronaut.io/latest/guide/index.html#usingsnapshots

**Comment by ilopmar** [comment]
Having said that, I'll release a new patch version of the module

**Comment by ilopmar** [comment]
I've released 3.1.1. Please give it some minutes until it's synchronized to Central: https://repo.maven.apache.org/maven2/io/micronaut/spring/micronaut-spring/

Apologies for the delay getting this version out with the fix

**Comment by ilopmar** [comment]
I've released 3.1.1. Please give it some minutes until it's synchronized to Central: https://repo.maven.apache.org/maven2/io/micronaut/spring/micronaut-spring/

Apologies for the delay getting this version out with the fix

**Comment by ilopmar** [comment]
I've released 3.1.1. Please give it some minutes until it's synchronized to Central: https://repo.maven.apache.org/maven2/io/micronaut/spring/micronaut-spring/

Apologies for the delay getting this version out with the fix
