### ISSUE TITLE
micronaut graal docker build issue

### ISSUE THREAD

**Issue by aarthisankaran** [micronaut-projects/micronaut-spring#23]
With micronautVersion=1.1.0.BUILD-SNAPSHOT
getting
Could not find or load main class io.micronaut.graal.reflect.GraalClassLoadingAnalyzer

**Comment by graemerocher** [comment]
Example updated to Micronaut 1.1 https://github.com/micronaut-projects/micronaut-spring/commit/5fdba1156b420ee1cde10230ab4f1b4fce6e05b9
