### ISSUE TITLE
Facing issue for decryption of environment variables using AWS KMS

### ISSUE THREAD

**Issue by nehaliacharya94** [micronaut-projects/micronaut-spring#26]
I have a SpringBoot application which I am migrating to Micronaut. This application reads the environment variables on AWS Lambda and the variables are encrypted using KMS. I used the SpringBootServletInitializer to get the variables from KMS and decrypt it before the data source formation. The same is not working in Micronaut. Could you help me proceed.

**Comment by ilopmar** [comment]
@nehaliacharya94 Can you please share a sample application that reproduces the issue?

**Comment by ilopmar** [comment]
Probably related to #18

**Comment by ilopmar** [comment]
Closing due to the lack of feedback.
