### ISSUE TITLE
Spring Security Support

### ISSUE THREAD

**Issue by mbagliojr** [micronaut-projects/micronaut-spring#27]
Does this support the @Secured annotation on http endpoints? It doesn't look like spring security is supported from the doc.

**Comment by jameskleeh** [comment]
@mbagliojr Can you clarify what you're trying to do? Is this a Grails app or a regular boot app? Or are you trying to use spring security in a Micronaut app?

**Comment by mbagliojr** [comment]
I have a spring boot application and I saw that it is possible to wrap a spring application in micronaut. I was looking to do this to ultimately leverage GraalVM which micronaut also supports but it seems as though I'm relying on some elements of Spring that you guys don't support, namely spring security.

**Comment by jameskleeh** [comment]
@mbagliojr Simply adding Micronaut on top of your existing boot app doesn't make the entire application compatible with GraalVM. In regards to the endpoints, assuming you are using the spring boot servlet environment, Micronaut has no bearing on the server.
