### ISSUE TITLE
Supporting the ability to import spring libraries in a Micronaut Application

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-spring#343]
### Issue description

The idea is that a company which has a library written in spring can import that code into a Micronaut application.

**Comment by jamesdh** [comment]
The inverse of this (but perhaps related): https://github.com/micronaut-projects/micronaut-spring/issues/270

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-spring/pull/332
