### ISSUE TITLE
URL mapping from RestController is ignored

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-spring#43]
URL prefix from `@RestController("/url/prefix")` is ignored and not translated to `@Controller("/url/prefix")`.

see https://github.com/micronaut-projects/micronaut-spring/blob/master/spring-web-annotation/src/main/java/io/micronaut/spring/web/annotation/RestControllerAnnotationMapper.java#L42

**Comment by graemerocher** [comment]
The value passed to `@RestController` is the logical bean name not a URI. See https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestController.html

**Comment by musketyr** [comment]
My fault. Thanks for pointing out
