### ISSUE TITLE
“More than 1 route matched the incoming request” when run native-image version of examples/greeting-service

### ISSUE THREAD

**Issue by ziyilin** [micronaut-projects/micronaut-spring#48]
Getting erroneous respond from the native compiled examples/greeting-service application.

```
$curl http://localhost:8080/greeting
{"message":"More than 1 route matched the incoming request. The following routes matched /greeting: GET - /greeting, GET - /greeting","_links":{"self":{"href":"/greeting","templated":false}}}
```
How to reproduce:
1. On branch `origin/graal-native-image`, apply this patch 
[0001-native-image-ready.txt](https://github.com/micronaut-projects/micronaut-spring/files/4235157/0001-native-image-ready.txt)
which adding necessary configurations so the examples/greeting-service can be compiled by GraalVM 19.3.0.2 and run successfully. 
2. run **svm.sh** to compile greeting-service into native-image. `$native_image` in the shell file should be set to your own _GraalVM/bin/native-image_.
3. start ./greeting-service
4. curl http://localhost:8080/greeting

This error does not happen in the Java Hotspot version, only in native compiled version.

**Comment by ilopmar** [comment]
@ziyilin where is the sample app?

**Comment by ilopmar** [comment]
Scratch that. It's a branch in this same repo.

The problem is you are including all the classes generated by the java agent. All the Micronaut classes are not necessary. Please try again removing all those classes.

**Comment by ziyilin** [comment]
It works when I delete the generatedConfigs/META-INF/native-image/resource-config.json generated by java agent. 
Thanks!

**Comment by ilopmar** [comment]
If you ever need to use the java agent keep it in mind and delete all the micronaut/netty entries there. For Micronaut are not necessary because it's reflection-free.
