### ISSUE TITLE
Why is @Transactional deprecated?

### ISSUE THREAD

**Issue by jimmytheneutrino** [micronaut-projects/micronaut-spring#73]
https://github.com/micronaut-projects/micronaut-spring/blob/04926c65609a6d8ff01c7f2c41b5c0ee323afc4d/spring/src/main/java/io/micronaut/spring/tx/annotation/Transactional.java#L58

The proposed replacement (Spring's transactional annotation) does not seem to work as is (using only micronaut-spring jar and even adding micronaut-spring-annotation:2.0.0). Maybe I am missing something else but could this something maybe be documented in the deprecation message?

**Comment by graemerocher** [comment]
`micronaut-spring-annotation` has to go on the annotation processor classpath

**Comment by jimmytheneutrino** [comment]
Thank you!
